### PR TITLE
Add windows build

### PR DESCRIPTION
**Pull request by thewchan**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by thewchan** [comment]
@conda-forge-admin, please rerender

**Comment by thewchan** [comment]
@asford looks like it successfully built for Windows, just having some mysterious fail in the travis CI build? I'm trying to get some pointers from the gitter. But otherwise I think this is ready to be merged?

**Comment by thewchan** [comment]
@conda-forge-admin, please rerender

**Review by asford — APPROVED** [review]
Lgtm

**Comment by thewchan** [comment]
@asford I switched travis to azure; all tests pass now. Thanks!

**Pull request merged**
